version: '3'
services:
    web:
        build: ./dockerfiles/web
        ports:
            - ${DOCKER_APACHE_80}:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        restart: always
        ports:
            - ${DOCKER_MYSQL_3306}:3306
        command:
            - --innodb-buffer-pool-size=64M
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DOCKER_MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_LOCAL_DATABASE}"
            MYSQL_USER: "${DB_LOCAL_USERNAME}"
            MYSQL_PASSWORD: "${DB_LOCAL_PASSWORD}"
